apiVersion: v1
kind: Secret
metadata:
  name: init-config-bundle-secret
  namespace: registry
data:
  config.yaml: QUxMT1dfUFVMTFNfV0lUSE9VVF9TVFJJQ1RfTE9HR0lORzogZmFsc2UKQVVUSEVOVElDQVRJT05fVFlQRTogRGF0YWJhc2UKREVGQVVMVF9UQUdfRVhQSVJBVElPTjogMncKRU5URVJQUklTRV9MT0dPX1VSTDogL3N0YXRpYy9pbWcvUkhfTG9nb19RdWF5X0JsYWNrX1VYLWhvcml6b250YWwuc3ZnCkZFQVRVUkVfQlVJTERfU1VQUE9SVDogZmFsc2UKRkVBVFVSRV9ESVJFQ1RfTE9HSU46IHRydWUKRkVBVFVSRV9NQUlMSU5HOiBmYWxzZQpSRUdJU1RSWV9USVRMRTogUmVkIEhhdCBRdWF5ClJFR0lTVFJZX1RJVExFX1NIT1JUOiBSZWQgSGF0IFF1YXkKU0VUVVBfQ09NUExFVEU6IHRydWUKVEFHX0VYUElSQVRJT05fT1BUSU9OUzoKLSAydwpURUFNX1JFU1lOQ19TVEFMRV9USU1FOiA2MG0KVEVTVElORzogZmFsc2UKRkVBVFVSRV9VU0VSX0lOSVRJQUxJWkU6IHRydWUKQlJPV1NFUl9BUElfQ0FMTFNfWEhSX09OTFk6IGZhbHNlClNVUEVSX1VTRVJTOgotIGFkbWluCg==

